language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
env:
  - TASK=test
before_install:
  - npm install -g ethereumjs-testrpc
before_script:
  - npm run bootstrap
  - npm prune
script:
  - testrpc &
  - npm run $TASK