sudo: required
services:
  - docker
language: node_js
cache:
  directories:
    - node_modules
    - apps/finance/node_modules
    - apps/finance/app/node_modules
    - apps/survey/node_modules
    - apps/survey/app/node_modules
    - apps/token-manager/node_modules
    - apps/token-manager/app/node_modules
    - apps/vault/node_modules
    - apps/voting/node_modules
    - apps/voting/app/node_modules
    - shared/migrations/node_modules
    - shared/minime/node_modules
    - shared/test-helpers/node_modules
notifications:
  email: false
node_js:
  - '8'
env:
  - TASK=test
  - TASK=lint
  - TASK=coverage
  - TASK=test:templates-beta
before_script:
  - npm prune
script:
  - npm run $TASK
after_success:
  - ./node_modules/.bin/lcov-result-merger 'apps/*/coverage/lcov.info' | ./node_modules/.bin/coveralls
