sudo: required
services:
  - docker
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
env:
  - TASK=lint
  - TASK=test:finance
  - TASK=test:survey
  - TASK=test:token-manager
  - TASK=test:vault
  - TASK=test:voting
  - TASK=coverage
  - TASK=test:shared
before_script:
  - npm prune
script:
  - npm run $TASK
after_success:
  - ./node_modules/.bin/lcov-result-merger 'apps/*/coverage/lcov.info' | ./node_modules/.bin/coveralls
